on:
    push:
        branches:
            - dev
jobs:
    lint:
        name: Lint Browser Extension Code
        runs-on: ubuntu-latest
        steps:
            - name: Get Repo
              uses: actions/checkout@v6
              with:
                spare-checkout: browserExtension
            - name: Lint files
              run: |
                cd browserExtension
                make \
                  NPX="docker run -v .:/work:z -w /work node:22.21.1-bookworm npx" \
                  MAGICK="docker run -v .:/work:z -w /work ghcr.io/ethanr555/imagemagicksvg:7.1.1-47-bookworm" \
                  NODE="docker run -v .:/work:z -w /work -i node:22.21.1-bookworm node" \
                  NPM="docker run -v .:/work:z -w /work node:22.21.1-bookworm npm" \
                  npm
                make \
                  NPX="docker run -v .:/work:z -w /work node:22.21.1-bookworm npx" \
                  MAGICK="docker run -v .:/work:z -w /work ghcr.io/ethanr555/imagemagicksvg:7.1.1-47-bookworm" \
                  NODE="docker run -v .:/work:z -w /work -i node:22.21.1-bookworm node" \
                  NPM="docker run -v .:/work:z -w /work node:22.21.1-bookworm npm" \
                  lint-nofix

    build:
        name: Build Browser Extension
        runs-on: ubuntu-latest
        steps:
            - name: Get Repo
              uses: actions/checkout@v6
              with:
                spare-checkout: browserExtension
            - name: Build
              run: |
                cd browserExtension
                make \
                  NPX="docker run -v .:/work:z -w /work node:22.21.1-bookworm npx" \
                  MAGICK="docker run -v .:/work:z -w /work ghcr.io/ethanr555/imagemagicksvg:7.1.1-47-bookworm" \
                  NODE="docker run -v .:/work:z -w /work -i node:22.21.1-bookworm node" \
                  NPM="docker run -v .:/work:z -w /work node:22.21.1-bookworm npm" \
                  npm
                make \
                  NPX="docker run -v .:/work:z -w /work node:22.21.1-bookworm npx" \
                  MAGICK="docker run -v .:/work:z -w /work ghcr.io/ethanr555/imagemagicksvg:7.1.1-47-bookworm" \
                  NODE="docker run -v .:/work:z -w /work -i node:22.21.1-bookworm node" \
                  NPM="docker run -v .:/work:z -w /work node:22.21.1-bookworm npm" \
                  build
                ls -Rl
            - name: Upload Build
              uses: actions/upload-artifact@v4
              with:
                path: browserExtension/build/
                name: BrowserExtension

    test:
        name: Test Browser Extension
        runs-on: ubuntu-latest
        needs: lint
        steps:
            - name: Get Repo
              uses: actions/checkout@v6
              with:
                spare-checkout: browserExtension
            - name: Test
              run: |
                cd browserExtension
                make \
                  NPX="docker run -v .:/work:z -w /work node:22.21.1-bookworm npx" \
                  MAGICK="docker run -v .:/work:z -w /work ghcr.io/ethanr555/imagemagicksvg:7.1.1-47-bookworm" \
                  NODE="docker run -v .:/work:z -w /work -i node:22.21.1-bookworm node" \
                  NPM="docker run -v .:/work:z -w /work node:22.21.1-bookworm npm" \
                  npm
                make \
                  NPX="docker run -v .:/work:z -w /work node:22.21.1-bookworm npx" \
                  MAGICK="docker run -v .:/work:z -w /work ghcr.io/ethanr555/imagemagicksvg:7.1.1-47-bookworm" \
                  NODE="docker run -v .:/work:z -w /work -i node:22.21.1-bookworm node" \
                  NPM="docker run -v .:/work:z -w /work node:22.21.1-bookworm npm" \
                  test
